### ISSUE TITLE
Rebase off of 2.7.0

### ISSUE THREAD

**Issue by davidbalbert** [geofft/qemu#4]
I have attached a diff created with `git format-patch` that with this repo rebased on top of 2.7.0. 

Here are the changes I had to make:
- Monitor.c has been restructured a bit in QEMU, so that the changes in the first two commits now belong in i386-target/monitor.c. This required declaring `pg_info` in include/monitor/hmp-target.h and making it non-static.
- The data structure that define monitor commands, their help text, etc. has been moved to hmp-commands-info.hx which uses some sort of macro language. It was not hard to port the changes.

IIRC, everything else remained the same.

It compiles and runs for me, and `info pg` seems to work, but I am not super familiar with the QEMU codebase or these patches, so please look them over.

I think the original committer info got clobbered in the patch file. My git-foo is not quite strong enough to know what to do about that.

[6.828-2.7.0.patch.txt](https://github.com/geofft/qemu/files/468710/6.828-2.7.0.patch.txt)

**Comment by geofft** [comment]
I missed seeing this issue come in, but I just pushed a rebase against 2.9.0 in the `6.828-2.9.0` branch, and your changes seem to match what I ended up with for monitor.c. Thanks!

**Comment by davidbalbert** [comment]
Great, thanks!
