### ISSUE TITLE
QEMU make error on Ubuntu 20.04

### ISSUE THREAD

**Issue by assawang** [geofft/qemu#6]
Hi，we build a docker with  Ubuntu 20.04 and try to make the newest version qemu in this docker，but it meet an error：
`util/memfd.c:40:12: error: static declaration of 'memfd_create' follows non-static declaration
   40 | static int memfd_create(const char *name, unsigned int flags)
      |            ^~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/mman-linux.h:113,
                 from /usr/include/x86_64-linux-gnu/bits/mman.h:34,
                 from /usr/include/x86_64-linux-gnu/sys/mman.h:41,
                 from /root/qemu/qemu/include/sysemu/os-posix.h:29,
                 from /root/qemu/qemu/include/qemu/osdep.h:104,
                 from util/memfd.c:28:
/usr/include/x86_64-linux-gnu/bits/mman-shared.h:50:5: note: previous declaration of 'memfd_create' was here
   50 | int memfd_create (const char *__name, unsigned int __flags) __THROW;
      |     ^~~~~~~~~~~~
make: *** [/root/qemu/qemu/rules.mak:69: util/memfd.o] Error 1
make: *** Waiting for unfinished jobs....`

**Comment by assawang** [comment]
someone has solved this problem with https://git.qemu.org/?p=qemu.git;a=commitdiff;h=75e5b70e6b5dcc4f2219992d7cffa462aa406af0;hp=200780a3a3ed067dfb2e0d2210b0ed09e748ba26 , can we merge this patch into this

**Comment by geofft** [comment]
This is not the upstream qemu repository. Are you specifically using the patches in this repository?

**Comment by assawang** [comment]
Yeah，I just use this repository to run jos in docker with ubuntu 20.04 image ，but met this problem when making qume，I'm trying to use lower version ubuntu such as 17.01 to solve this problem。Thank you

**Comment by assawang** [comment]
I tried ubuntu v14.04 and  `git submodule update --init dtc` then succeed
